export const sacrificeSets = [
	{
		name: "Desayuno",
		backgroundColor: "#F2A65A",
		color: "#5B2E1A",
		items: [
			"Café",
			"Pan tostado",
			"Croissant",
			"Miel",
			"Canela",
			"Mermelada",
			"Chocolate",
			"Galletas",
		],
	},
	{
		name: "Animalitos",
		backgroundColor: "#79B4A9",
		color: "#353535",
		items: [
			"Gatito",
			"Perrito",
			"Pajarito",
			"Tortuguita",
			"Conejito",
			"Patito",
			"Erizo",
			"Ranita",
		],
	},
	{
		name: "Postres",
		backgroundColor: "#E78FB3",
		color: "#4A1E33",
		items: [
			"Helado",
			"Paleta",
			"Brownie",
			"Alfajor",
			"Torta",
			"Cupcake",
			"Churro",
			"Flan",
		],
	},
	{
		name: "Cosas lfacheras facheritas",
		backgroundColor: "#F6C453",
		color: "#5B3E00",
		items: [
			"Siesta",
			"Abrazos",
			"Risas",
			"Música",
			"Sol",
			"Lluvia",
			"Fegos artificiales",
			"Globos",
		],
	},
	{
		name: "Afectos",
		backgroundColor: "#D97EA8",
		color: "#3E1229",
		items: [
			"Besos",
			"Amistad",
			"Familia",
			"Mascotas",
			"Mimos",
			"Cariño",
			"Ternura",
			"Compañía",
		],
	},
	{
		name: "Naturaleza",
		backgroundColor: "#6FA96C",
		color: "#1E3B1D",
		items: [
			"Bosques",
			"Océanos",
			"Montañas",
			"Flores",
			"Árboles",
			"Ríos",
			"Estrellas",
			"Arcoíris",
		],
	},
	{
		name: "Diversión",
		backgroundColor: "#7EC8E3",
		color: "#0F3550",
		items: [
			"Videojuegos",
			"Fiestas",
			"Vacaciones",
			"Bailar",
			"Cine",
			"Juegos de mesa",
			"Parques de diversiones",
			"Chistes",
		],
	},
	{
		name: "Comfort food",
		backgroundColor: "#C97B4A",
		color: "#3A1F0D",
		items: [
			"Pizza",
			"Asado",
			"Empanadas",
			"Milanesas",
			"Fideos",
			"Pancitos calentitos",
			"Sopa",
			"Papas fritas",
		],
	},
	{
		name: "Momentos simples",
		backgroundColor: "#A0A8D8",
		color: "#242850",
		items: [
			"Dormir hasta tarde",
			"Ver series",
			"Leer un libro",
			"Escuchar la lluvia",
			"Charlar con amigos",
			"Tomar mate",
			"Caminar sin apuro",
			"Días de sol en la plaza",
		],
	},
	{
		name: "Cultura y arte",
		backgroundColor: "#B98FD1",
		color: "#331E42",
		items: [
			"Música en vivo",
			"Pinturas",
			"Libros",
			"Películas",
			"Museos",
			"Teatro",
			"Fotografía",
			"Poesía",
		],
	},
];
